app:
    resource: '@AppBundle/Controller/'
    type: annotation

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

users:
    type:     rest
   # host:     m.example.com
    resource: AppBundle\Controller\TestController